print("nothing")
print("nothinsdfsdfg")
print("i am sick of trying to figure this shit out")
print("I think I figured it out")
print("nothing")
print("nothinsdfsdfg")
print("i am sick of trying to figure this shit out")
print("I think I figured it out")